name: Dependabot auto merge

on: pull_request

jobs:
  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
